CREATE DATABASE ATIVIDADEDELETAR
USE ATIVIDADEDELETAR

SELECT * FROM ALUNO
SELECT * FROM PROFESSOR
SELECT * FROM FUNCIONARIO
SELECT * FROM MATERIAS

CREATE TABLE ALUNO(
	RA INT PRIMARY KEY,
	NOME VARCHAR(250),
	IDADE VARCHAR(250)
)

CREATE TABLE PROFESSOR(
	RP INT PRIMARY KEY,
	NOME VARCHAR(250),
	IDADE VARCHAR(250)
)

CREATE TABLE FUNCIONARIO(
	RF INT PRIMARY KEY,
	NOME VARCHAR(250),
	IDADE VARCHAR(250)
)

CREATE TABLE MATERIAS(
	ID INT PRIMARY KEY,
	DESCRICAO VARCHAR(250)
	
)

INSERT INTO ALUNO VALUES(1,'Camila','20')
INSERT INTO ALUNO VALUES(2,'Caio','22')
INSERT INTO ALUNO VALUES(3,'Alison','24')
INSERT INTO ALUNO VALUES(4,'Guilherme','34')
INSERT INTO ALUNO VALUES(5,'Paulo','13')

INSERT INTO PROFESSOR VALUES(1,'Omar','30')
INSERT INTO PROFESSOR VALUES(2,'Joel','28')
INSERT INTO PROFESSOR VALUES(3,'Muriel','29')
INSERT INTO PROFESSOR VALUES(4,'Jean','56')
INSERT INTO PROFESSOR VALUES(5,'Rodrigo','44')

INSERT INTO FUNCIONARIO VALUES(1,'Carlos','30')
INSERT INTO FUNCIONARIO VALUES(2,'Teddy','20')
INSERT INTO FUNCIONARIO VALUES(3,'Mauro','35')
INSERT INTO FUNCIONARIO VALUES(4,'Rogeria','45')
INSERT INTO FUNCIONARIO VALUES(5,'Adriana','34')

INSERT INTO MATERIAS VALUES(1,'Programação Web')
INSERT INTO MATERIAS VALUES(2,'Programação Mobile')
INSERT INTO MATERIAS VALUES(3,'Redes de Computadores')
INSERT INTO MATERIAS VALUES(4,'Interação Humano Computador')
INSERT INTO MATERIAS VALUES(5,'Modelagem de Software')



