USE [ATIVIDADEDELETAR]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[ProcedureDeletar]
@tabela varchar(250)
AS
DECLARE @SQL NVARCHAR(250) = 'DELETE FROM '+ @tabela
 EXEC (@SQL)