CREATE DATABASE AtividadeCRUD
USE AtividadeCRUD

CREATE TABLE CLIENTES(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(250),
	SOBRENOME VARCHAR(250),
	CPF VARCHAR(20),
)

select * from CLIENTES

